from time import sleep
print('\033[31m-=-\033[m'*20)
print('Empréstimo bancário', end='')
print('.', end='')
sleep(1)
print('.', end='')
sleep(1)
print('.')
sleep(1)
print('\033[31m-=-\033[m'*20)
casa = float(input('Qual o valor da casa R$ '))
salario = float(input('Qual seu salario? '))
anos = int(input('Anos de financiamento: '))
prestacao = casa / (anos * 12)
minimo = salario * 0.3
print('\033[31m-=-\033[m'*20)
print(f'Para pegar uma casa de R${casa:.2f} em {anos} anos, a prestação será de R${prestacao:.2f}')
print('\033[31m-=-\033[m'*20)
sleep(1)
print('Checando se o financiamento será possivel, aguarde', end='')
print('.', end='')
sleep(2)
print('.', end='')
sleep(2)
print('.')
sleep(2)
if prestacao <= minimo:
    print(f'PARABÉNS! O empréstimo foi concedido!')
else:
    print('NEGADO! O empréstimo não foi possivel ser concedido por conta do seu salario ser menor que a minima!')
print('\033[31m-=-\033[m'*20)